### ISSUE TITLE
Snapshot state cleanup for Nodes not part of cluster but stuck in non-aborted state

### ISSUE THREAD

**Issue by ignoramous** [imotov/elasticsearch-snapshot-cleanup#8]
There are cases where in 1.x and 2.x Elasticsearch we have encountered that nodes that are not part of the cluster anymore are part of the Snapshot metadata and report SUCCESS / INIT / STARTED and various other states, but the _overall_ snapshot state is ABORTED.

In the current script, cleanup happens only if the missing nodes report ABORTED state (shard snapshot state). 

The question I have is: Why not clean up regardless of what the shard snapshot state reported is (since the _overall_ snapshot state is ABORTED).

```
// shard snapshot state of a missing node with SUCCESS state
        "shards" : [ {
          "index" : "logstash-something",
          "shard" : 1,
          "state" : "SUCCESS",
          "node" : "some-missing-node" // missing node
        }
// overall snapshot state, ABORTED
      "snapshots" : [ {
        "repository" : "some-snapshot-repo",
        "snapshot" : "some-snapshot-id",
        "include_global_state" : true,
        "state" : "ABORTED", 
        "indices" : [ ...
```

Specifically [this line](https://github.com/imotov/elasticsearch-snapshot-cleanup/blob/master/src/main/java/org/motovs/elasticsearch/snapshots/AbortedSnapshotCleaner.java#L75) can be changed to: 

```
if (entry.state() == ABORTED && clusterState.clusterState.nodes().get(nodeId) == null) {
```

DELETE doesn't work in these cases either. 

@imotov Could you chime here, pls?

**Comment by imotov** [comment]
First of all, this utility was created to solve one very specific issue. The goal was to minimize possible issues if this utility is abused or used in a situations that it wasn't designed to handle. It is also important to note the the issue that this utility is trying to solve were fixed in 2.x in the elasticsearch itself. 

To answer your question, if the state of a particular shard is SUCCESS while the state of the snapshot is ABORTED, it means that the shard finished processing before the snapshot was cancelled. Such shards don't prevent the snapshot from being completed and there is no need to delete them from the cluster state. Moreover, deleting them would create a lot of noise and make the whole process much slower then needed.

**Comment by ignoramous** [comment]
Thanks. We have seen other shard states too, not just `SUCCESS`. If I understand right, all other shard snapshot states other than `ABORTED`, wouldn't prevent _overall_ snapshot from being _completed_?

**Comment by imotov** [comment]
Which version of elasticsearch is it?

**Comment by ignoramous** [comment]
elasticsearch version is `1.5.x`.

There are three distinct cases (the overall state is `ABORTED` in  all of these, and _delete_ doesn't work, it just hangs):

1. Nodes that are missing are in one of `ABORTED` or `SUCCESS` or `FAILED` state for different shards.

2. The nodes that are _not_ missing, are also in one of `ABORTED`, `SUCCESS`, or `FAILED` states.

3. In some cases, _all_ nodes reported in _SnapshotState_ are missing from the _ClusterState_.

Tangential question: Is there a design doc / writeup about SnapshotService internals? For instance, there's `SnapshotMetaData.State.xyz` and there's `IndexShardSnapshotStatus.Stage.xyz` Unsure what they mean. It looks like there's a nice state machine underneath the SnapshotsService, but it'd be great if there's a public documentation of it somewhere that documents the internals and intended behaviour.

BTW, can't thank you enough for for all your hard work and diligently listening to queries and answering them from all quarters.

**Comment by imotov** [comment]
There is no documentation the I am aware off besides that you can find on our web site and in SnapshotService java docs.

1.5.x [EOLed](https://www.elastic.co/support/eol) more than a year ago and has serious known stability and security issues, you should upgrade to 1.7.6 ASAP and consider migration to  6.x in the nearest future. 

This utility was created to deal with the case 1. So, it should help here.

What you are describing in the case 2. can happen if the snapshot process on the node is stuck and cannot be aborted. In this case you need to restart the node to ensure full cleanup instead of running this utility. Hacking this utility to work in such case will most likely lead to some data loss. 

The 3rd use case might indicate that the issues that you are experiencing with snapshot/restore are just symptoms of other more serious issues that are causing stability issues, node disconnects, cluster state propagations issues, etc. Perhaps you have outgrown your cluster, or perhaps you are hitting one of the known stability issues in 1.5 that were fixed years ago. 

Unfortunately, 1.5 is about 3 years old, and we moved majority of our users off it relatively quickly, so I simply don't remember everything that was wrong with 1.5 release, I just remember that we fixed a lot of snapshot/restore bugs in 1.6 and 1.7 (and even more [resiliency](https://www.elastic.co/guide/en/elasticsearch/resiliency/current/index.html) related bugs in 2.x and 5.x ). That also means that general community and developers' expertise in 1.5 is quite reduced since the number of engineers who dealt with 1.5 recently is very small. So, I think upgrading would be the only sensible solution here. If you need any help with the upgrade process, please don't hesitate to ask at https://discuss.elastic.co/ Asking questions about 1.5 might there might be less useful since the most likely answer that you are going to get is a suggestion to upgrade, which is again the recommendation that I would give.

**Comment by ignoramous** [comment]
> 1.5.x EOLed more than a year ago and has serious known stability and security issues

Thanks. I guess I'd push to prioritize upgrading in the coming months.

> What you are describing in the case 2. can happen if the snapshot process on the node is stuck and cannot be aborted. In this case you need to restart the node to ensure full cleanup instead of running this utility. 

Any es-command that would reveal more diagnostics about snapshot service (other than debug logs, which aren't enabled)? The JVM heap usage (mostly around 50%) seem to be fine, but I get that during the snapshotting process anything could have happened (master-failover, JVM stop-the-world GC, process-crash etc;). We're not using the Azure plugin... so no threads are stuck doing IO. 

Just to double check, I'd need to run this tool to get rid of nodes stuck in case #1, and restart the nodes (kill -15 the es-process in the nodes) in case #2.

> Hacking this utility to work in such case will most likely lead to some data loss.

Data loss in the node, or data loss wrt to what's stored in the Snapshots? If the latter, I think we're fine. Obv, not okay with the former (but then again, we would have moved to 6.x if we cared enough about durability :).

> The 3rd use case might indicate that the issues that you are experiencing with snapshot/restore are just symptoms of other more serious issues that are causing stability issues, node disconnects, cluster state propagations issues, etc. 

Would forcing master-state-sync in this case help? Or more precisely, does master state going out-of-sync affect snapshots and they're forever hung in `ABORTED` state?

**Comment by imotov** [comment]
> Just to double check, I'd need to run this tool to get rid of nodes stuck in case #1, and restart the nodes (kill -15 the es-process in the nodes) in case #2.

Correct

> Or more precisely, does master state going out-of-sync affect snapshots and they're forever hung in ABORTED state?

Indeed. It affects everything in your cluster including snapshot process.

Regarding everything else, if you still have issues after the upgrade I would be glad to help you with them on Elastic's discussion forum https://discuss.elastic.co/
